export enum EventActivity {
  DRAWING = 'DRAWING',
  DRAW_SUCCESS = 'DRAW_SUCCESS',
  NOT_ORDERABLE = 'NOT_ORDERABLE',
  LOCKED_POINTS = 'LOCKED_POINTS',
  UNLOCKED_POINTS = 'UNLOCKED_POINTS',

  REFRESH = 'REFRESH',
}
