export enum UserNotificationType {
  EVENT_SESSION_PREPARE_DRAW = 'EVENT_SESSION_PREPARE_DRAW',
  EVENT_SESSION_DRAWING = 'EVENT_SESSION_DRAWING',
  EVENT_SESSION_DRAW_SUCCESS = 'EVENT_SESSION_DRAW_SUCCESS',

  DAILY_JACKPOT_PREPARE_DRAW = 'DAILY_JACKPOT_PREPARE_DRAW',
  DAILY_JACKPOT_DRAWING = 'DAILY_JACKPOT_DRAWING',
  DAILY_JACKPOT_DRAW_SUCCESS = 'DAILY_JACKPOT_DRAW_SUCCESS',

  WEEKLY_JACKPOT_PREPARE_DRAW = 'WEEKLY_JACKPOT_PREPARE_DRAW',
  WEEKLY_JACKPOT_DRAWING = 'WEEKLY_JACKPOT_DRAWING',
  WEEKLY_JACKPOT_DRAW_SUCCESS = 'WEEKLY_JACKPOT_DRAW_SUCCESS',

  MONTHLY_JACKPOT_PREPARE_DRAW = 'MONTHLY_JACKPOT_PREPARE_DRAW',
  MONTHLY_JACKPOT_DRAWING = 'MONTHLY_JACKPOT_DRAWING',
  MONTHLY_JACKPOT_DRAW_SUCCESS = 'MONTHLY_JACKPOT_DRAW_SUCCESS',

  DEPOSIT_REQUEST_APPROVED = 'DEPOSIT_REQUEST_APPROVED',
}
