export enum VerificationType {
  EMAIL_REGISTER = 'EMAIL_REGISTER',
  EMAIL_RESET_PASSWORD = 'EMAIL_RESET_PASSWORD',
  PHONE_REGISTER = 'PHONE_REGISTER',
  PHONE_RESET_PASSWORD = 'PHONE_RESET_PASSWORD',
}
