export enum WalletActivity {
  APPROVE_DEPOSIT_REQUEST = 'APPROVE_DEPOSIT_REQUEST',
  CREATED_WITHDRAW_REQUEST = 'CREATED_WITHDRAW_REQUEST',
  CANCEL_WITHDRAW_REQUEST = 'CANCEL_WITHDRAW_REQUEST',
  APPROVE_WITHDRAW_REQUEST = 'APPROVE_WITHDRAW_REQUEST',
  TOP_UP = 'TOP_UP',
  REFRESH = 'REFRESH',
}
