export enum WalletHistoryType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  TRANSFER_EVENT_ORDER = 'TRANSFER_EVENT_ORDER',
  TRANSFER_JACKPOT_ORDER = 'TRANSFER_JACKPOT_ORDER',
  REWARD_EVENT_SESSION = 'REWARD_EVENT_SESSION',
  WIN_DAILY_JACKPOT = 'WIN_DAILY_JACKPOT',
  WIN_WEEKLY_JACKPOT = 'WIN_WEEKLY_JACKPOT',
  WIN_MONTHLY_JACKPOT = 'WIN_MONTHLY_JACKPOT',
}
